New Version with further DataAPI support
SkylineCommunications/SLC-UDAPI-DataAPI-Proxy pull request #1
Opened 2024-11-18 14:15 UTC by JoaoSE-Skyline

2024-11-19 16:54 UTC, SkylineThomasCR requested changes

2024-11-19 16:54 UTC, SkylineThomasCR commented on README.md
> +# UDAPI-DataAPI-Proxy
```suggestion
# A Proxy to Access Data API Externally

[DataMiner Data API](https://docs.dataminer.services/user-guide/Advanced_Modules/Data_Sources/Data_API.html) is an [upcoming feature](https://community.dataminer.services/scripted-connectors-are-here/) that enables the automated creation and modification of custom elements using raw values sent via JSON data. 
This data is directly reflected in the element, and it can be easily updated using the same API, eliminating the need to develop a connector.

Currently, Data API is restricted to local use, typically through Scripted Connectors. 
This [User-Defined API](https://docs.dataminer.services/user-guide/Advanced_Modules/User-Defined_APIs/UD_APIs.html) offers a proof-of-concept solution for remote access, 
functioning as a secure reverse proxy to enable external interaction with the Data API.

This documentation explains how to set up and use the **UDAPI-DataAPI-Proxy** to extend Data API functionality beyond the local DataMiner instance.

> [!NOTE]
> Use with caution, as every data push triggers a script run to pass data to the Data API.

## Prerequisites

- **DataMiner 10.4.2 or higher**.
- A **cloud-connected DataMiner agent** with the User Defined API deployed.

## Setting Up the Proxy Script

### Step 1: Deploy the Script

Deploy the script from the catalog onto your cloud-enabled DataMiner system.

### Step 2: Configure the User Defined API

- Configure the User Defined API to expose Data API as an external API interface with endpoints: `data/parameters` and `data/config`.
- Use **Raw body** for method execution.
- Secure the API with a **Bearer Token**.

For full details on setting up and managing User Defined APIs and tokens, refer to [User-Defined APIs - Managing APIs and Tokens in DataMiner Cube](https://docs.dataminer.services/user-guide/Advanced_Modules/User-Defined_APIs/UD_APIs_Viewing_in_Cube.html).

![Configure User Defined API](/Documentation/2_configure_API.png)  
![Data API User Defined API](/Documentation/1_UD_API.png)

### Step 3: Use Data API via the proxy

Use an HTTP client (e.g., [Postman](https://www.postman.com/)) to send data to DataMiner via Data API through the proxy.

1. **Set Up the Endpoint**  
   In this example, the endpoint to send data to DataMiner and automatically create an element is:
   ```
   api/custom/data/parameters
   ```
   Set the request verb to **PUT**.

1. **Add URL Encoded Parameters**
   When pushing data to DataMiner, you need to provide two URL parameters:
   - `identifier`: A unique identifier (e.g., `DataAPI Test Element 1`). This will be used as the name of the new element.
   - `type`: The type of the auto-generated connector (e.g., `Skyline DataAPI Test Protocol`).

    ![Add URL encoded parameters](/Documentation/3_URL_encoded_parameters.png)

    > [!NOTE]
    > Each element requires a `unique identifier`, but can share a `type`. Elements that share a `type` will share the same parameters and layout, but can still have distinct parameter data.

1. **Configure JSON in the Body**
   The JSON with the parameter data used in this example:

   ```json
   {
     "Server Name": "WebServer001",
     "CPU Utilization": 78.5
   }
   ```

1. **Configure the Bearer Token**
   In Postman, configure the **Authorization tab** to use the **Bearer Token** you configured in Step 2.

1. **Send the Request**  
   Send the PUT request. The result will indicate whether the operation was successful (_200 OK_), or provide feedback in case of failure.

### Result: Dynamic Element Creation

After executing the command:
- A new element will appear in your DataMiner system.
- Every update you send afterward will be instantly visible in the element.

## Conclusion

By deploying and configuring this proxy script, you can securely access Data API features from external clients. This is a proof-of-concept solution, future DataMiner updates may offer direct external access to the Data API, simplifying this workflow.
```

2024-11-19 16:54 UTC, SkylineThomasCR commented on README.md
> +# UDAPI-DataAPI-Proxy
you will need to restore 2_configure_API.png

2024-11-20 09:02 UTC, JoaoSE-Skyline commented on UDAPI-DataAPI-Proxy_1/UDAPI-DataAPI-Proxy_1.cs
> +			// /fW4SXxfiXzirU1bH5+9IHu13u4kX2oUaiAR/NzMjtU=
Indeed, forgot to remove it, it was a local test token that is no longer valid

2024-11-20 15:17 UTC, SkylineThomasCR approved these changes

2024-11-26 12:13 UTC, merged